name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Windows Server
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./gradlew build
      - name: Publish
        run: ./gradlew publish
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
        if: github.event_name == 'push'


  # macOS Catalina
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Publish
        run: ./gradlew publish
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
        if: github.event_name == 'push'

  # Ubuntu 18.04 LTS
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Publish
        run: ./gradlew publish
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
        if: github.event_name == 'push'
      - name: Deploy Vendor JSON
        run: curl -u ghactions:${{ secrets.ARTIFACTORY_API_KEY }}! -X PUT "https://maven.photonvision.org/artifactory/libs-release/photonlib.json" -T vendordeps/photonlib.json
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
        if: github.event_name == 'push'


  # roboRIO
  build-roborio:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2020-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build -Ponlylinuxathena
      - name: Publish
        run: ./gradlew publish -Ponlylinuxathena
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
        if: github.event_name == 'push'


  # Raspbian
  build-raspbian:
    runs-on: ubuntu-latest
    container: wpilib/raspbian-cross-ubuntu:10-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build -Ponlylinuxraspbian
      - name: Publish
        run: ./gradlew publish -Ponlylinuxraspbian
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
        if: github.event_name == 'push'


  # Linux Aarch64
  build-linux-aarch64:
    runs-on: ubuntu-latest
    container: wpilib/aarch64-cross-ubuntu:bionic-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build -Ponlylinuxaarch64bionic
      - name: Publish
        run: ./gradlew publish -Ponlylinuxaarch64bionic
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
        if: github.event_name == 'push'
